export const endpoints = {
  login: "/auth/login",
  signup: "/auth/signup",
  profile: "/user/profile",
  emails: "/emails",
  documents: "/documents",
  deadlines: "/deadlines",
  tasks: "/tasks",
  calendar: "/calendar/events",
  reminders: "/reminders",
  notifications: "/notifications",
  integrations: "/integrations",
  aiChat: "/ai/chat",
  aiActions: "/ai/actions",
  aiSearch: "/ai/search",
  knowledge: "/knowledge/search",
  insights: "/insights",
  privacy: "/privacy",
};
